version: '3.8'

services:
  app:
    build:
      shm_size: 512m
    volumes:
      - ./app:$WORK_DIR:cached
      - vscode-extension-volume:$HOME_DIR/.vscode-server/extensions
      - ./.devcontainer/devcontainer-entrypoint.sh:$HOME_DIR/etc/devcontainer-entrypoint.sh
    user: $USER_ID:$GROUP_ID
    entrypoint:
      - bash
      - $HOME_DIR/etc/devcontainer-entrypoint.sh
    ports:
      - $IP:9229:9229
      - $IP:6080:80
    command: >
      bash -c 'npx playwright install &&
      sleep infinity'
    # command: sleep infinity


volumes:
  vscode-extension-volume: {}
